import { getAllMosquesWithRevenueSummary, getMosqueRevenue } from "@/lib/actions/revenue";
import { Sparkles, Star, DollarSign, Building2 } from "lucide-react";

export const metadata = { title: "Mosque Revenue | Admin" };

interface Props {
  searchParams: Promise<{ mosque?: string }>;
}

export default async function RevenuePage({ searchParams }: Props) {
  const { mosque: selectedMosqueId } = await searchParams;

  const [summaries, detail] = await Promise.all([
    getAllMosquesWithRevenueSummary(),
    selectedMosqueId ? getMosqueRevenue(selectedMosqueId) : null,
  ]);

  const totalPlatformMRR = summaries.reduce((sum, m) => sum + m.totalMRR, 0);
  const selectedMosque = summaries.find((m) => m.id === selectedMosqueId);

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Mosque Revenue</h1>
        <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Revenue generated by businesses affiliated with each mosque</p>
      </div>

      {/* Platform total */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <StatCard icon={<DollarSign className="h-5 w-5 text-emerald-600" />} label="Total Platform MRR" value={`$${totalPlatformMRR.toFixed(0)} CAD`} bg="bg-emerald-50 dark:bg-emerald-900/10" />
        <StatCard icon={<Sparkles className="h-5 w-5 text-violet-600" />} label="Active Sponsored" value={summaries.reduce((s, m) => s + m.sponsoredCount, 0).toString()} bg="bg-violet-50 dark:bg-violet-900/10" />
        <StatCard icon={<Star className="h-5 w-5 text-amber-600" />} label="Active Featured" value={summaries.reduce((s, m) => s + m.featuredCount, 0).toString()} bg="bg-amber-50 dark:bg-amber-900/10" />
      </div>

      {/* Mosque list */}
      <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl overflow-hidden">
        <div className="px-5 py-4 border-b border-gray-100 dark:border-gray-800">
          <h2 className="font-semibold text-gray-900 dark:text-white text-sm">Revenue by Mosque</h2>
          <p className="text-xs text-gray-400 mt-0.5">Click a mosque to see a detailed breakdown</p>
        </div>
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-gray-100 dark:border-gray-800 text-xs text-gray-400 uppercase tracking-wide">
              <th className="text-left px-5 py-3">Mosque</th>
              <th className="text-right px-5 py-3">Sponsored</th>
              <th className="text-right px-5 py-3">Featured</th>
              <th className="text-right px-5 py-3">MRR</th>
              <th className="px-5 py-3" />
            </tr>
          </thead>
          <tbody>
            {summaries.map((m) => (
              <tr
                key={m.id}
                className={`border-b border-gray-50 dark:border-gray-800/50 hover:bg-gray-50 dark:hover:bg-gray-800/40 transition-colors ${selectedMosqueId === m.id ? "bg-emerald-50/50 dark:bg-emerald-900/10" : ""}`}
              >
                <td className="px-5 py-3.5">
                  <div className="flex items-center gap-2.5">
                    <div className="h-8 w-8 rounded-lg bg-emerald-100 dark:bg-emerald-900/30 flex items-center justify-center">
                      <Building2 className="h-4 w-4 text-emerald-600" />
                    </div>
                    <div>
                      <p className="font-medium text-gray-900 dark:text-white">{m.name}</p>
                      {m.city && <p className="text-xs text-gray-400">{m.city}</p>}
                    </div>
                  </div>
                </td>
                <td className="px-5 py-3.5 text-right">
                  <span className="inline-flex items-center gap-1 text-xs font-medium text-violet-700 dark:text-violet-400 bg-violet-50 dark:bg-violet-900/20 px-2 py-0.5 rounded-full">
                    <Sparkles className="h-3 w-3" /> {m.sponsoredCount}
                  </span>
                </td>
                <td className="px-5 py-3.5 text-right">
                  <span className="inline-flex items-center gap-1 text-xs font-medium text-amber-700 dark:text-amber-400 bg-amber-50 dark:bg-amber-900/20 px-2 py-0.5 rounded-full">
                    <Star className="h-3 w-3" /> {m.featuredCount}
                  </span>
                </td>
                <td className="px-5 py-3.5 text-right font-semibold text-gray-900 dark:text-white">
                  {m.totalMRR > 0 ? `$${m.totalMRR.toFixed(0)}` : <span className="text-gray-300 dark:text-gray-600 font-normal">—</span>}
                </td>
                <td className="px-5 py-3.5 text-right">
                  <a
                    href={`/admin/revenue?mosque=${m.id}`}
                    className="text-xs text-emerald-700 dark:text-emerald-400 hover:underline font-medium"
                  >
                    Details →
                  </a>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Mosque detail */}
      {detail && selectedMosque && (
        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-lg font-bold text-gray-900 dark:text-white">{detail.mosque?.name}</h2>
              <p className="text-sm text-gray-500">{detail.mosque?.city}</p>
            </div>
            <div className="text-right">
              <p className="text-2xl font-bold text-emerald-600">${detail.totalMRR.toFixed(0)} <span className="text-sm font-normal text-gray-400">CAD/mo</span></p>
              <p className="text-xs text-gray-400">${detail.sponsoredMRR.toFixed(0)} sponsored + ${detail.featuredMRR.toFixed(0)} featured</p>
            </div>
          </div>

          {/* Sponsored listings */}
          {detail.sponsored.length > 0 && (
            <div className="bg-white dark:bg-gray-900 border border-violet-200 dark:border-violet-800/50 rounded-xl overflow-hidden">
              <div className="px-5 py-3 border-b border-violet-100 dark:border-violet-800/30 flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-violet-600" />
                <span className="font-semibold text-sm text-gray-900 dark:text-white">Sponsored Listings</span>
                <span className="ml-auto text-xs font-medium text-violet-700">${detail.sponsoredMRR.toFixed(0)} CAD/mo</span>
              </div>
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-xs text-gray-400 uppercase tracking-wide border-b border-gray-100 dark:border-gray-800">
                    <th className="text-left px-5 py-2">Business</th>
                    <th className="text-left px-5 py-2">Category</th>
                    <th className="text-right px-5 py-2">MRR</th>
                    <th className="text-right px-5 py-2">Since</th>
                  </tr>
                </thead>
                <tbody>
                  {detail.sponsored.map((l: any) => (
                    <tr key={l.id} className="border-b border-gray-50 dark:border-gray-800/50">
                      <td className="px-5 py-3 font-medium text-gray-900 dark:text-white">
                        {l.professional.businessName || `${l.professional.user.firstName} ${l.professional.user.lastName}`}
                      </td>
                      <td className="px-5 py-3 text-gray-500">{l.professional.category.name}</td>
                      <td className="px-5 py-3 text-right font-semibold text-violet-700">${Number(l.priceMonthly).toFixed(0)}</td>
                      <td className="px-5 py-3 text-right text-gray-400 text-xs">{l.startDate ? new Date(l.startDate).toLocaleDateString("en-CA", { month: "short", year: "numeric" }) : "—"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Featured listings */}
          {detail.featured.length > 0 && (
            <div className="bg-white dark:bg-gray-900 border border-amber-200 dark:border-amber-800/50 rounded-xl overflow-hidden">
              <div className="px-5 py-3 border-b border-amber-100 dark:border-amber-800/30 flex items-center gap-2">
                <Star className="h-4 w-4 text-amber-500" />
                <span className="font-semibold text-sm text-gray-900 dark:text-white">Featured Listings</span>
                <span className="ml-auto text-xs font-medium text-amber-700">${detail.featuredMRR.toFixed(0)} CAD/mo</span>
              </div>
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-xs text-gray-400 uppercase tracking-wide border-b border-gray-100 dark:border-gray-800">
                    <th className="text-left px-5 py-2">Business</th>
                    <th className="text-left px-5 py-2">City</th>
                    <th className="text-right px-5 py-2">Impressions</th>
                    <th className="text-right px-5 py-2">Clicks</th>
                    <th className="text-right px-5 py-2">MRR</th>
                  </tr>
                </thead>
                <tbody>
                  {detail.featured.map((l: any) => (
                    <tr key={l.id} className="border-b border-gray-50 dark:border-gray-800/50">
                      <td className="px-5 py-3 font-medium text-gray-900 dark:text-white">
                        {l.professional.businessName || `${l.professional.user.firstName} ${l.professional.user.lastName}`}
                      </td>
                      <td className="px-5 py-3 text-gray-500">{l.city || "—"}</td>
                      <td className="px-5 py-3 text-right text-gray-500">{l.impressions.toLocaleString()}</td>
                      <td className="px-5 py-3 text-right text-gray-500">{l.cardClicks.toLocaleString()}</td>
                      <td className="px-5 py-3 text-right font-semibold text-amber-700">${Number(l.priceMonthly).toFixed(0)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {detail.sponsored.length === 0 && detail.featured.length === 0 && (
            <div className="text-center py-10 text-gray-400 text-sm bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl">
              No active paid listings for this mosque yet.
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function StatCard({ icon, label, value, bg }: { icon: React.ReactNode; label: string; value: string; bg: string }) {
  return (
    <div className={`${bg} border border-gray-200 dark:border-gray-800 rounded-xl p-4 flex items-center gap-3`}>
      <div className="h-10 w-10 rounded-lg bg-white dark:bg-gray-900 flex items-center justify-center shadow-sm flex-shrink-0">
        {icon}
      </div>
      <div>
        <p className="text-xs text-gray-500 dark:text-gray-400">{label}</p>
        <p className="text-xl font-bold text-gray-900 dark:text-white">{value}</p>
      </div>
    </div>
  );
}
